### ISSUE TITLE
html does not link to atom.xml using rss meta tags

### ISSUE THREAD

**Issue by iki** [browniefed/browniefed.github.io#1]

**Comment by browniefed** [comment]
Hmmm my site gets auto-generated by octopress.
The `atom.xml` is here [http://browniefed.com/atom.xml](http://browniefed.com/atom.xml) and appears to be valid.
EDIT: Nevermind I understand. Will fix this.

**Comment by browniefed** [comment]
I've popped
`<link rel="alternate" type="application/atom+xml" title="JavaScript Without Grammar" href="http://browniefed.com/atom.xml">` on there. Thank you for the report. If you have any more issues do let me know.
